services:
  frontend:
    image: ashorta/frontend_1
    container_name: frontend_1
    build:
      context: ./client
    stdin_open: true
    depends_on:
      - backend
    ports:
      - 3000:3000
    
  backend:
    image: ashorta/backend_1
    container_name: backend_1
    build:
      context: ./backend
    stdin_open: true
    depends_on:
      - mongo_db
    ports:
      - 5000:5000
    environment:
      - MONGODB_URI=mongodb://mongo:27017/
  
  mongo:
    image: mongo
    container_name: mongo_db
    restart: always
    ports:
      - 27017:27017

